# Generated by Django 4.0.4 on 2022-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
