# Generated by Django 4.0.4 on 2022-05-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecog', '0006_temp_name_alter_posts_image_alter_temp_img_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postpeople',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postpeople',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postpeople',
            name='username',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.RemoveField(
            model_name='userface',
            name='username',
        ),
        migrations.DeleteModel(
            name='PostPeople',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Userface',
        ),
    ]
