# Generated by Django 4.0.4 on 2022-05-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faceRecog', '0007_alter_postpeople_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/user.jpeg', upload_to='dp/')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.PositiveBigIntegerField()),
                ('profile_pic', models.ImageField(default='images/user.jpeg', upload_to='dp/')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Userface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_face', models.ImageField(default='images/user.jpeg', upload_to='faces/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceRecog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user.jpeg', upload_to='posts/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceRecog.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceRecog.posts')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceRecog.user')),
            ],
            options={
                'unique_together': {('username', 'post_id')},
            },
        ),
    ]
