# Generated by Django 4.0.3 on 2022-05-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecog', '0009_delete_temp_remove_user_admin_remove_user_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
