# Generated by Django 4.0.3 on 2022-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecog', '0012_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpeople',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
