# Generated by Django 4.0.3 on 2022-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecog', '0013_postpeople_is_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userface',
        ),
    ]
